Repository DeveloperAcademy-POSTECH/MC3-Team9-F4, pull requests merged in 2023-07, with the labels that each got.

#5 [Setting]Tering#4-색상 및 테니스 공 추가
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Assets.xcassets/Color/Black.colorset/Contents.json
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Assets.xcassets/Color/Contents.json
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Assets.xcassets/Color/Gray.colorset/Contents.json
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Assets.xcassets/Color/LightBlack.colorset/Contents.json
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Assets.xcassets/Color/LightBlue.colorset/Contents.json
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Assets.xcassets/Color/LightGreen.colorset/Contents.json
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Assets.xcassets/Color/Pink.colorset/Contents.json
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Assets.xcassets/tennisBall.imageset/Contents.json
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Assets.xcassets/tennisBall.imageset/tennisBall.png
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Extension/ColorExtension.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
Labels: Setting

#7 [Feat]Tering#6-스윙목록뷰 레이아웃
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/ContentView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/MC3_F4_DoWonGyoRiApp.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Model/SwingList.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListCellView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
Labels: Feat

#11 [Feat]Tering#8-가이드, 개수 뷰 네비게이션 완료
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/MC3_F4_DoWonGyoRiApp.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Model/SwingList.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/GuideView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingCountView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListCellView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
Labels: Feat

#13 [ Design]Tering#10-스윙 개수뷰 레이아웃 작성
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ReadyView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingCountView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
Labels: Design

#25 Feature/#14WatchOS-준비 뷰 구현
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Extension/CircleProgressBar.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ReadyView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
Labels: Feat

#27 Feature/#15-WatchOS-남은 횟수 뷰 및 측정 중 뷰 연결
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Assets.xcassets/Color/LightRed.colorset/Contents.json
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Extension/ColorExtension.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/MeasuringView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ReadyView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
Labels: Feat

#28 Feature/#17: WatchOS- 측정 뷰 레이아웃
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/MeasuringView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ReadyView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingResultView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
Labels: Feat

#29 Feature/#18: WatchOS-스윙 완료 뷰 완성
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Extension/CircleProgressBar.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CompleteView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ReadyView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ResultView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
Labels: Feat

#30 Feature/#19
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Extension/CircleProgressBar.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Extension/ColorExtension.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CompleteView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ResultView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListCellView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListView.swift
Labels: Feat

#35 Feature/#31 [Feat]WatchOS-네비게이션 수정
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CompleteView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/MeasuringView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ReadyView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ResultView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingCountView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingResultView.swift
Labels: Feat

#37 [Feat]#36-요약뷰2번 레이아웃 완료
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Extension/CircleProgressBar.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ResultView.swift
Labels: Feat

#40 Feature/#38:WatchOS-요약뷰 3번째 레이아웃
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ResultView.swift
Labels: Feat, Design

#49 [Design]#46-디자인 레이아웃 지정
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Extension/CircleProgressBar.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CompleteView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ReadyView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ResultView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingCountView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingResultView.swift
Labels: Design

#53 Feature/#41 NavigationStack 관련
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/MC3_F4_DoWonGyoRiApp.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Model/SwingList.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/MeasuringView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ResultView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingCountView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Feat

#71 [Feat]#16-측정 중 뷰 완성 및 List CarouselListStyle 적용
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/MeasuringView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListView.swift
Labels: Feat

#72 Feature/#44 WatchOS- 폭죽 난리뷰 완성
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Model/Particle.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Model/ParticleEffect.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ResultView.swift
  MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
Labels: Feat

#88 Feature/#73 WatchConnectivity 연동
  MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
  MC3_Tering/MC3_Tering/Model/ViewModelPhone.swift
  MC3_Tering/MC3_Tering/View/TestPhoneView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/MC3_Tering_WatchApp.swift
  MC3_Tering/MC3_Tering_Watch Watch App/Model/HealthResultInfo.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/CountingView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/SwingCountView.swift
Labels: Feat

#91 [ Feat]#90-디지털 크라운 완성
  MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
  MC3_Tering/MC3_Tering_Watch Watch App/View/SwingCountView.swift
Labels: Feat

#95 Feature/#93 WatchOS-디지털 크라운 버튼 제작 완료
  MC3_Tering/MC3_Tering_Watch Watch App/View/SwingCountView.swift
Labels: Feat

#96 [Add]#94 - watchOS 앱에 ML모델 및 관련 클래스 추가
  MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
  MC3_Tering/MC3_Tering_Watch Watch App/MLModel/TennisClassifierViewModel.swift
  MC3_Tering/MC3_Tering_Watch Watch App/MLModel/TeringClassifier_totalData_window100.mlmodel
  MC3_Tering/MC3_Tering_Watch Watch App/MLModel/TeringClassifier_totalData_window200.mlmodel
Labels: Add

#103 Feature/#100 WatchOS- 뷰 연결하기
  MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
  MC3_Tering/MC3_Tering_Watch Watch App/MC3_Tering_WatchApp.swift
  MC3_Tering/MC3_Tering_Watch Watch App/Model/SwingInfo.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/CountingView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/MeasuringView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/ReadyView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/SwingCountView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/SwingResultView.swift
Labels: Feat

#111 Feature/#104 WatchOS-스윙횟수뷰 관련 기능 완성
  MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
  MC3_Tering/MC3_Tering_Watch Watch App/MLModel/TennisClassifierViewModel.swift
  MC3_Tering/MC3_Tering_Watch Watch App/Model/SwingInfo.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/CountingView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/MeasuringView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/ReadyView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/SelectView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/SwingCompleteView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/SwingCountView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/SwingResultView.swift
Labels: Feat

#112 Design/#105 WatchOS- 자잘한 수정
  MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
  MC3_Tering/MC3_Tering_Watch Watch App/Extension/CircleProgressBar.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/MeasuringView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/SwingCompleteView.swift
Labels: Design

#113 Feature/#106 WatchOS- 햅틱 넣기
  MC3_Tering/MC3_Tering_Watch Watch App/MC3_Tering_WatchApp.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/CountingView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/MeasuringView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/SwingCountView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/SwingListView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/SwingResultView.swift
Labels: Feat

#120 [Feat]#119-스윙 데이터 넘겨주기
  MC3_Tering/MC3-Tering-Watch-Watch-App-Info.plist
  MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
  MC3_Tering/MC3_Tering/Model/ViewModelPhone.swift
  MC3_Tering/MC3_Tering/View/TestPhoneView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView.swift
Labels: Feat
