Repository DeveloperAcademy-POSTECH/MC3-Team9-F4, pull requests merged in 2023-08, with the labels that each got.

#141 [Feat] 10초 미만 운동 저장하지 않는 로직 추가 #139
  MC3_Tering/MC3_Tering_Watch Watch App/Model/WorkoutManager.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView/ResultView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/CountingView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/SelectView.swift
Labels: Feat

#142 [Del] watchOS 불필요 주석 및 코드 삭제하기 #126
  MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
  MC3_Tering/MC3_Tering_Watch Watch App/MLModel/TennisClassifierViewModel.swift
  MC3_Tering/MC3_Tering_Watch Watch App/Model/HealthKitManager.swift
  MC3_Tering/MC3_Tering_Watch Watch App/Model/HealthStartInfo.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView/ResultView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/StartView/SwingCountView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/CountingView.swift
Labels: Del

#147 [Feat]#146- Core Data 워치에 인식
  MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
  MC3_Tering/MC3_Tering/Model/WorkOutDataModel.swift
  MC3_Tering/MC3_Tering_Watch Watch App/MC3_Tering_WatchApp.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/EtcView/CompleteView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView/ResultView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/CountingView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/SelectView.swift
Labels: Feat

#151 [Design] 워치 화면 레이아웃 조정 및 재디자인 #148
  MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
  MC3_Tering/MC3_Tering_Watch Watch App/View/EtcView/TestLayoutView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView/ResultView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/CountingView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/SelectView.swift
Labels: Design

#156 Feature/#150 WatchOS Core Data 연동
  MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
  MC3_Tering/MC3_Tering/Model/CoreData/UserInfo.xcdatamodeld/UserInfo.xcdatamodel/contents
  MC3_Tering/MC3_Tering/Model/CoreData/WorkOutData/WorkOutData+CoreDataClass.swift
  MC3_Tering/MC3_Tering/Model/CoreData/WorkOutData/WorkOutData+CoreDataProperties.swift
  MC3_Tering/MC3_Tering/Model/ViewModelPhone.swift
  MC3_Tering/MC3_Tering/Model/WorkOutDataModel.swift
  MC3_Tering/MC3_Tering/View/MainView/MainView.swift
  MC3_Tering/MC3_Tering/View/MainView/RecordListView/RecordListView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/MC3_Tering_WatchApp.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/EtcView/CompleteView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView/ResultView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/CountingView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/SelectView.swift
Labels: Feat

#160 [Fix] watchOS 관련 코드 정리 #159
  MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
  MC3_Tering/MC3_Tering_Watch Watch App/Extension/CircleProgressBar.swift
  MC3_Tering/MC3_Tering_Watch Watch App/MC3_Tering_WatchApp.swift
  MC3_Tering/MC3_Tering_Watch Watch App/MLModel/TennisClassifierViewModel.swift
  MC3_Tering/MC3_Tering_Watch Watch App/MLModel/TeringClassifier_totalData_window200.mlmodel
  MC3_Tering/MC3_Tering_Watch Watch App/Model/Particle/Particle.swift
  MC3_Tering/MC3_Tering_Watch Watch App/Model/Particle/ParticleEffect.swift
  MC3_Tering/MC3_Tering_Watch Watch App/Model/SwingList.swift
  MC3_Tering/MC3_Tering_Watch Watch App/Model/ViewModelWatch.swift
  MC3_Tering/MC3_Tering_Watch Watch App/Model/Workout/SwingInfo.swift
  MC3_Tering/MC3_Tering_Watch Watch App/Model/Workout/WorkoutManager.swift
  MC3_Tering/MC3_Tering_Watch Watch App/Model/Workout/WorkoutResultInfo.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/EtcView/ContentView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/EtcView/GuideView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/EtcView/SwingListCellView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/EtcView/SwingListView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/EtcView/Ted_CountingView/TedCountingView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/EtcView/TestWatchView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView/ResultView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/StartView/ReadyView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/StartView/SwingCountView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/Complete/SelectView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/Complete/SwingCompleteView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/CountingView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/Measurement/MeasuringView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/Measurement/SwingResultView.swift
Labels: Fix

#164 [Fix] 운동 결과 데이터 중복 저장 문제 해결 및 watchOS 최적화 작업 #159, #161
  MC3_Tering/MC3_Tering/View/MainView/MainView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/MC3_Tering_WatchApp.swift
  MC3_Tering/MC3_Tering_Watch Watch App/Model/Workout/WorkoutManager.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView/ResultView.swift
  MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/CountingView.swift
Labels: Fix
